cc_library(
    name = "DatabaseLib",
    srcs = ["database.cc"],
    hdrs = [
        "Idatabase.h",
        "database.h",
        "database_element.h",
    ],
    visibility = ["//app:__subpackages__"],
    deps = ["@core"],
)
