cc_library(
    name = "JsonParser",
    hdrs = ["database_json_parser.h"],
    visibility = ["//app:__subpackages__"],
    deps = [
        "//app/database:DatabaseLib",
        "@com_json//:json",
    ],
)
